# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Greater Brisbane
email: hello@greaterbrisbane.org
description: >- # this means to ignore newlines until "baseurl:"
  For abundant housing and livable communities.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.greaterbrisbane.org" # the base hostname & protocol for your site, e.g. http://example.com
lang: "en-AU"
# authorisation: >-

# OpenGraph relevant settings
author: 
  name: "Greater Brisbane" #{ change to legal name of association once incorporated}
  twitter: greaterbne

logo: "/assets/images/favicon.png"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-url-metadata
# show posts even if they seem to have a date in the future at build time
future: true

# For the links at the bottom of the site
# social_links:
#   - { platform: discord,         name: "Discord",         url: "https://discord.gg/fcr74BgzZU" }
#   - { platform: github,        name: "greaterbrisbane",         url: "https://github.com/greaterbrisbane" }
#   - { platform: linkedin,      name: "LinkedIn",         url: "https://www.linkedin.com/company/greaterbrisbane" }
#   - { platform: twitter,       name: "Twitter",         url: "https://twitter.com/greaterbne" }
#   - { platform: rss,      name: "Feed",         url: "/feed.xml" }

# Minima-specific settings
minima:
  skin: auto
  social_links:
    - { platform: discord,  title: "Discord",  user_url: "https://discord.gg/fcr74BgzZU" }
    - { platform: github,   title: "GitHub",   user_url: "https://github.com/greaterbrisbane" }
    - { platform: linkedin, title: "LinkedIn", user_url: "https://www.linkedin.com/company/greaterbrisbane" }
    - { platform: twitter,  title: "Twitter",  user_url: "https://twitter.com/greaterbne" }
    - { platform: rss,      title: "Feed",     user_url: "/feed.xml" }

header_pages:
  - blog.md
  - newsletter.md

# Various settings live under the "defaults" key
defaults:
  - scope:
      path: ""
    values:
        image: "/assets/images/favicon.png"
  - scope:
      path: "_posts"
    values:
      layout: post


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to extend the default setting.
# exclude:
